# Generated by Django 4.1.7 on 2023-03-01 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promotionapplicant", old_name="City", new_name="address",
        ),
        migrations.AddField(
            model_name="promotionapplicant",
            name="gender",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="promotionapplicant",
            name="province",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Api.province",
            ),
            preserve_default=False,
        ),
    ]
