# Generated by Django 4.1.7 on 2023-03-02 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Api", "0002_rename_city_promotionapplicant_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grandpricedraw",
            name="draw_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="grandpricedraw",
            name="province",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Api.province",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="promotionweeklydraw",
            name="draw_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="promotionweeklydraw",
            name="province",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Api.province",
            ),
            preserve_default=False,
        ),
    ]
