# Generated by Django 4.1.7 on 2023-03-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Api", "0003_grandpricedraw_draw_number_grandpricedraw_province_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="vlicDb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Regno", models.CharField(max_length=100)),
                ("Status", models.CharField(max_length=100)),
                ("Penalties", models.IntegerField(default=0, max_length=100)),
                ("Arrears", models.IntegerField(default=0, max_length=100)),
                ("DateLicensed", models.DateField()),
                ("ExpiryDate", models.DateField()),
                ("dateCaptured", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="promotionweeklydraw", options={"ordering": ["id"]},
        ),
    ]
