# Generated by Django 4.1.7 on 2023-03-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Api", "0004_vlicdb_alter_promotionweeklydraw_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseDb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("REGISTRATION_NO", models.CharField(max_length=100)),
                ("LICENSE_STATUS", models.CharField(max_length=100)),
                ("PENALTY_AMOUNT", models.IntegerField(default=0)),
                ("ARREAR_AMOUNT", models.IntegerField(default=0)),
                ("LAST_LICENSING_TRANSACTION", models.DateTimeField()),
                ("BLACKLISTED", models.CharField(max_length=100)),
                ("LICENCE_EXPIRY_DATE", models.DateTimeField()),
                ("Date_Captured", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
