# Generated by Django 4.1.7 on 2023-03-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Api", "0005_licensedb"),
    ]

    operations = [
        migrations.AddField(
            model_name="licensedb",
            name="EXPIRED",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
