# Generated by Django 4.1.7 on 2023-03-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Api", "0006_licensedb_expired"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licensedb",
            name="EXPIRED",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vlicdb", name="Arrears", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="vlicdb", name="Penalties", field=models.IntegerField(default=0),
        ),
    ]
