# Generated by Django 3.2.6 on 2023-10-04 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_alter_licensedb_expired_alter_vlicdb_arrears_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_class', models.CharField(choices=[('0', 'Motorcyles'), ('1', 'Light vehicles'), ('2', 'Buses'), ('3', 'Heavy vehicles'), ('4', 'Haulage trucks')], max_length=1)),
                ('vehicle_mass', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('T', 'Tolling fee'), ('L', 'Vehicle licensing fee'), ('B', 'Bridge fee'), ('R', 'Transit fee')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.vehicleclass')),
            ],
        ),
    ]
