# Generated by Django 3.2.6 on 2023-11-03 19:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_tariff_vehicleclass'),
    ]
    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=20)),
                ('document_number', models.CharField(max_length=20, unique=True)),
                ('reg_book_document', models.ImageField(null=True, upload_to='kyc/')),
            ],
        ),
        migrations.AlterField(
            model_name='tariff',
            name='fee_type',
            field=models.CharField(choices=[('Toll', 'Tolling fee'), ('Liv', 'Vehicle licensing fee'), ('Bridge', 'Bridge fee'), ('Transit', 'Transit fee')], max_length=10),
        ),
        migrations.CreateModel(
            name='VehicleOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('national_identity', models.EmailField(max_length=100, unique=True)),
                ('national_identity_document_image', models.ImageField(upload_to='kyc/{1}/identity/')),
                ('kyc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_owner', to='Api.kyc')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCurrentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('national_identity', models.EmailField(max_length=100, unique=True)),
                ('national_identity_document_image', models.ImageField(null=True, upload_to='kyc/{1}/identity/')),
                ('kyc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_current_user', to='Api.kyc')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=1)),
                ('license_plate', models.CharField(max_length=10, unique=True)),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='Api.vehiclecurrentuser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='Api.vehicleowner')),
            ],
        ),
        migrations.CreateModel(
            name='DataCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_collection', to='Api.vehicle')),
            ],
        ),
    ]
