# Generated by Django 3.2.6 on 2023-11-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_employee_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='code',
            new_name='codes',
        ),
    ]
